https://github.com/bhaveshkumarraj/Deep-Neural-Network-Linear-Regression

In [1]:
import numpy as np
import urllib.request as urllib
from sklearn.preprocessing import StandardScaler,MinMaxScaler,LabelEncoder,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Dense

G:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
# 预处理数据
labelEncoder=LabelEncoder()
oneHotEncoder=OneHotEncoder(categorical_features=[0])
ss=StandardScaler()

1.标准化StandardScaler
1.1 概述
我们知道，在训练模型的时候，要输入features,即因子，也叫特征。对于同一个特征，不同的样本中的取值可能会相差非常大，一些异常小或异常大的数据会误导模型的正确训练；另外，如果数据的分布很分散也会影响训练结果。以上两种方式都体现在方差会非常大。此时，我们可以将特征中的值进行标准差标准化，即转换为均值为0，方差为1的正态分布。所以在训练模型之前，一定要对特征的数据分布进行探索，并考虑是否有必要将数据进行标准化。

标准差标准化也叫作Z-zero标准化，经过处理的数据会符合标准正态分布，即均值为0，方差为1。转化函数为：

x* = (x - μ) /σ
1
公式中标准化后的值x* 等于 原来的值x先减去原数据的均值μ，然后在除以原数据的标准差σ。最后得到的新的数据的均值就是0，方差/标准差为1.

注：是否要进行标准化，要根据具体实验定。如果特征非常稀疏，并且有大量的0（现实应用中很多特征都具有这个特点），Z-score 标准化的过程几乎就是一个除0的过程，结果不可预料。

In [69]:
url = "http://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"
raw_data = urllib.urlopen(url)
DataMatrix = np.loadtxt(raw_data, dtype=str, delimiter=',')
X=DataMatrix[:,:8]
y=DataMatrix[:,8]

In [71]:
# https://blog.csdn.net/appleyuchi/article/details/73503282 关于label encoder 的介绍
# 先fit，然后transform 和fit_transform一样
print(X[:,0])
labelEncoder.fit(X[:,0])
print(labelEncoder.classes_)
t_x1=labelEncoder.transform(X[:,0])
print(t_x1)

t_x2=labelEncoder.fit_transform(X[:,0])
print(t_x2)

['M' 'M' 'F' ... 'M' 'F' 'M']
['F' 'I' 'M']
[2 2 0 ... 2 0 2]
[2 2 0 ... 2 0 2]


In [72]:
# 关于onehotencoder的介绍在这里
X[:,0] = labelEncoder.fit_transform(X[:,0])
X = oneHotEncoder.fit_transform(X).toarray()
X_train, X_test, y_train, y_test = train_test_split(X,y)
X_train = ss.fit_transform(X_train)
X_test = ss.transform(X_test)
scaler = MinMaxScaler().fit(y_train.reshape(-1,1))
y_train = scaler.transform(y_train.reshape(-1,1))
print(y.shape)
y_test  = scaler.transform(y_test.reshape(-1,1))

(4177,)


G:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype <U6 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


In [61]:
# Neural Network
prediction_network = Sequential()
prediction_network.add(Dense(units=10, kernel_initializer='uniform', activation='relu', input_dim=10))
prediction_network.add(Dense(units=10, kernel_initializer='uniform', activation = 'relu'))
prediction_network.add(Dense(units=1, kernel_initializer='uniform'))
prediction_network.compile(optimizer='adam', loss='mean_squared_error', metrics=['accuracy'])

# Fitting model
prediction_network.fit(X_train, y_train, batch_size=10, epochs=50)

# Predict the test set
y_pred = prediction_network.predict(X_test)
rmse = mean_squared_error(y_test, y_pred)
print("Root Mean Square Error : {:.4f}".format(rmse))


Epoch 1/50
3132/3132 [==============================] - 1s 286us/step - loss: 0.0270 - acc: 3.1928e-04
Epoch 2/50
3132/3132 [==============================] - 0s 151us/step - loss: 0.0077 - acc: 3.1928e-04
Epoch 3/50
3132/3132 [==============================] - 1s 179us/step - loss: 0.0067 - acc: 3.1928e-04
Epoch 4/50
3132/3132 [==============================] - 1s 193us/step - loss: 0.0066 - acc: 3.1928e-04
Epoch 5/50
3132/3132 [==============================] - 0s 158us/step - loss: 0.0064 - acc: 3.1928e-04
Epoch 6/50
3132/3132 [==============================] - 0s 145us/step - loss: 0.0063 - acc: 3.1928e-04
Epoch 7/50
3132/3132 [==============================] - 0s 159us/step - loss: 0.0063 - acc: 3.1928e-04
Epoch 8/50
3132/3132 [==============================] - 0s 143us/step - loss: 0.0063 - acc: 3.1928e-04
Epoch 9/50
3132/3132 [==============================] - 0s 156us/step - loss: 0.0063 - acc: 3.1928e-04
Epoch 10/50
3132/3132 [==============================] - 0s 139us/step - 

In [62]:
y_pred = prediction_network.predict(X_test)
print(y_pred)

[[0.25961435]
 [0.5486993 ]
 [0.3924645 ]
 ...
 [0.47147053]
 [0.40588295]
 [0.22125278]]


In [64]:
y_test

array([[0.25925926],
       [0.44444444],
       [0.33333333],
       ...,
       [0.2962963 ],
       [0.44444444],
       [0.25925926]])