参考：

https://jizhi.im/blog/post/10min2pandas01

http://pandas.pydata.org/pandas-docs/stable/10min.html

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#创建一个Series对象：传递一个数值列表作为参数，令Pandas使用默认索引
s=pd.Series([1,3,5,np.nan,6,8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64


In [ ]:
#创建一个DataFrame对象:传递datetime索引和列表签的Numpy数组作为参数
#首先创建一个时间序列
dates=pd.date_range('20130101',periods=6)
print(dates)
#创建DataFrame对象，指定index和columns标签
df=pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
print(df)

In [6]:
#观察数据
#查看一个DataFrame对象的前几行和最后几行
print(df.head())
print(df.tail(3))
#默认情况下 .head()和.tail()输出首尾的前5行，也可以指定输出行数

                   A         B         C         D
2013-01-01  0.508963 -0.033850 -1.102689 -1.074022
2013-01-02 -2.006031 -0.199846  1.551850  0.513289
2013-01-03 -0.642342  1.327011 -0.312336 -1.740733
2013-01-04 -0.951646 -1.977274 -0.065789  1.866246
2013-01-05  0.017630 -0.465354  1.227774 -2.033067
                   A         B         C         D
2013-01-04 -0.951646 -1.977274 -0.065789  1.866246
2013-01-05  0.017630 -0.465354  1.227774 -2.033067
2013-01-06 -0.408561  0.684235  1.401449 -1.562944


In [7]:
#查看索引
print(df.index)
#列表签
print(df.columns)
#数值
print(df.values)
#统计
print(df.describe())

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')
[[ 0.50896273 -0.03384979 -1.10268864 -1.0740221 ]
 [-2.00603076 -0.1998463   1.55184982  0.51328885]
 [-0.64234168  1.32701117 -0.31233634 -1.74073316]
 [-0.95164564 -1.97727362 -0.06578932  1.86624618]
 [ 0.01763029 -0.46535356  1.2277738  -2.03306673]
 [-0.40856091  0.68423466  1.40144867 -1.56294408]]
              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.580331 -0.110846  0.450043 -0.671872
std    0.865790  1.124514  1.093828  1.536079
min   -2.006031 -1.977274 -1.102689 -2.033067
25%   -0.874320 -0.398977 -0.250700 -1.696286
50%   -0.525451 -0.116848  0.580992 -1.318483
75%   -0.088918  0.504714  1.358030  0.116461
max    0.508963  1.327011  1.551850  1.866246


In [8]:
# 灵活调教你的DataFrame
#转置
print(df.T)
#按列排序，逐步递减
print(df.sort_index(axis=1,ascending=False))
#按值排序，‘B’列逐行递增
print(df.sort_values(by='B'))

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    0.508963   -2.006031   -0.642342   -0.951646    0.017630   -0.408561
B   -0.033850   -0.199846    1.327011   -1.977274   -0.465354    0.684235
C   -1.102689    1.551850   -0.312336   -0.065789    1.227774    1.401449
D   -1.074022    0.513289   -1.740733    1.866246   -2.033067   -1.562944
                   D         C         B         A
2013-01-01 -1.074022 -1.102689 -0.033850  0.508963
2013-01-02  0.513289  1.551850 -0.199846 -2.006031
2013-01-03 -1.740733 -0.312336  1.327011 -0.642342
2013-01-04  1.866246 -0.065789 -1.977274 -0.951646
2013-01-05 -2.033067  1.227774 -0.465354  0.017630
2013-01-06 -1.562944  1.401449  0.684235 -0.408561
                   A         B         C         D
2013-01-04 -0.951646 -1.977274 -0.065789  1.866246
2013-01-05  0.017630 -0.465354  1.227774 -2.033067
2013-01-02 -2.006031 -0.199846  1.551850  0.513289
2013-01-01  0.508963 -0.033850 -1.102689 -1.074022
2013-01-06 -0.4085

In [9]:
#选中
#获取
print(df["A"])#与df.A相同
print(df.A)
#使用[]分割DataFrame
print(df[0:3])
print(df['20130102':'20130104'])

2013-01-01    0.508963
2013-01-02   -2.006031
2013-01-03   -0.642342
2013-01-04   -0.951646
2013-01-05    0.017630
2013-01-06   -0.408561
Freq: D, Name: A, dtype: float64
2013-01-01    0.508963
2013-01-02   -2.006031
2013-01-03   -0.642342
2013-01-04   -0.951646
2013-01-05    0.017630
2013-01-06   -0.408561
Freq: D, Name: A, dtype: float64
                   A         B         C         D
2013-01-01  0.508963 -0.033850 -1.102689 -1.074022
2013-01-02 -2.006031 -0.199846  1.551850  0.513289
2013-01-03 -0.642342  1.327011 -0.312336 -1.740733
                   A         B         C         D
2013-01-02 -2.006031 -0.199846  1.551850  0.513289
2013-01-03 -0.642342  1.327011 -0.312336 -1.740733
2013-01-04 -0.951646 -1.977274 -0.065789  1.866246


In [10]:
#按标签选择
#选中一行
print(df.loc(dates[0]))
#标签选中复制数列（所有行，输出只显示前5行）
print(df.loc[:,['A','B']])
#行，列同时切分（包括起止点）
print(df.loc['20130102':'20130104',['A','B']])
#返回一个元素（两种等效）
print(df.loc[dates[0],'A'])
print(df.at[dates[0],'A'])

                   A         B
2013-01-01  0.508963 -0.033850
2013-01-02 -2.006031 -0.199846
2013-01-03 -0.642342  1.327011
2013-01-04 -0.951646 -1.977274
2013-01-05  0.017630 -0.465354
2013-01-06 -0.408561  0.684235
                   A         B
2013-01-02 -2.006031 -0.199846
2013-01-03 -0.642342  1.327011
2013-01-04 -0.951646 -1.977274
0.508962730383
0.508962730383


In [16]:
#按位置选择
#位置索引为3的列，（从0开始，所以其实是第4列）
print(df)
print(df.iloc[3])
#按位置索引分割DataFrame
print(df.iloc[3:5,0:2])
#指定定位一个特定元素
print(df.iloc[1,1])
print(df.iat[1,1])

                   A         B         C         D
2013-01-01  0.508963 -0.033850 -1.102689 -1.074022
2013-01-02 -2.006031 -0.199846  1.551850  0.513289
2013-01-03 -0.642342  1.327011 -0.312336 -1.740733
2013-01-04 -0.951646 -1.977274 -0.065789  1.866246
2013-01-05  0.017630 -0.465354  1.227774 -2.033067
2013-01-06 -0.408561  0.684235  1.401449 -1.562944
A   -0.951646
B   -1.977274
C   -0.065789
D    1.866246
Name: 2013-01-04 00:00:00, dtype: float64
                   A         B
2013-01-04 -0.951646 -1.977274
2013-01-05  0.017630 -0.465354
-0.199846298258
-0.199846298258


In [21]:
#布尔值索引
print(df.A>0)
#使用.isin函数过滤数据
df2=df.copy()
df2

2013-01-01     True
2013-01-02    False
2013-01-03    False
2013-01-04    False
2013-01-05     True
2013-01-06    False
Freq: D, Name: A, dtype: bool


A         B         C         D
2013-01-01  0.508963 -0.033850 -1.102689 -1.074022
2013-01-02 -2.006031 -0.199846  1.551850  0.513289
2013-01-03 -0.642342  1.327011 -0.312336 -1.740733
2013-01-04 -0.951646 -1.977274 -0.065789  1.866246
2013-01-05  0.017630 -0.465354  1.227774 -2.033067
2013-01-06 -0.408561  0.684235  1.401449 -1.562944

In [26]:
df2['E']=['one','one','two','three','four','three']
#提取df2中'E'值属于['two','four']的行
print(df2[df2['E'].isin(['two','four'])])

                   A         B         C         D     E
2013-01-03 -0.642342  1.327011 -0.312336 -1.740733   two
2013-01-05  0.017630 -0.465354  1.227774 -2.033067  four


In [43]:
#为DataFrame创建一个新的列，其值为时间顺序的索引值
s1=pd.Series([1,2,3,4,5,6],index=pd.date_range('20130101',periods=6))
print(s1)
df['F']=s1
#按标签赋值
df.at[dates[0],'A']=0
#按索引赋值
df.iat[0,1]=0
#使用numpy数组赋值
df.loc[:,'D']=np.array([5]*len(df))
print(len(df))
print(df)

2013-01-01    1
2013-01-02    2
2013-01-03    3
2013-01-04    4
2013-01-05    5
2013-01-06    6
Freq: D, dtype: int64
6
                   A         B         C  D  F
2013-01-01  0.000000  0.000000 -1.102689  5  1
2013-01-02 -2.006031 -0.199846  1.551850  5  2
2013-01-03 -0.642342  1.327011 -0.312336  5  3
2013-01-04 -0.951646 -1.977274 -0.065789  5  4
2013-01-05  0.017630 -0.465354  1.227774  5  5
2013-01-06 -0.408561  0.684235  1.401449  5  6


In [53]:
#创建Dataframe对象，以dates[0:4]为索引，在df基础上再加一个新的‘E’列
df1=df.reindex(index=dates[0:4],columns=list(df.columns)+['E'])
#将'E'列的前两个行设为1
df1.loc[dates[0]:dates[1],'E']=1
print(df1)

                   A         B         C  D  F    E
2013-01-01  0.000000  0.000000 -1.102689  5  1  1.0
2013-01-02 -2.006031 -0.199846  1.551850  5  2  1.0
2013-01-03 -0.642342  1.327011 -0.312336  5  3  NaN
2013-01-04 -0.951646 -1.977274 -0.065789  5  4  NaN


In [58]:
#处理缺失数据
#去除df1中含NaN的行
df1.dropna(how='any')
#使用5填充缺省值
df1.fillna(value=5)
#判断df1中的致是否为缺失数据，返回True/False
pd.isnull(df1)

A      B      C      D      F      E
2013-01-01  False  False  False  False  False  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

[pandas 中的Axis（轴）含义](https://blog.csdn.net/qq_16234613/article/details/76223188) 
![](https://img-blog.csdn.net/20170727234536310?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvcXFfMTYyMzQ2MTM=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/SouthEast)

axis=0指的是逐行，axis=1指的是逐列。

In [3]:
df=pd.DataFrame([[1,1,1,1],[2,2,2,2],[3,3,3,3]],columns=['col1','col2','col3','col4'])
df

col1  col2  col3  col4
0     1     1     1     1
1     2     2     2     2
2     3     3     3     3

In [4]:
print(df.mean(axis=0))#mean(axis=0)计算的是每一列平均值， 

col1    2.0
col2    2.0
col3    2.0
col4    2.0
dtype: float64


In [5]:
print(df.mean(axis=1))#mean(axis=1)计算的是每一行平均值。 


0    1.0
1    2.0
2    3.0
dtype: float64


In [6]:
print(df.drop(0,axis=0))# drop(0,axis=0)删除行， 


   col1  col2  col3  col4
1     2     2     2     2
2     3     3     3     3


In [12]:
print(df.drop('col1',axis=1))  #drop([‘col1’],axis=1)删除列。

   col2  col3  col4
0     1     1     1
1     2     2     2
2     3     3     3


## pandas中reset_index的用法
重新设置索引

In [3]:
df = pd.DataFrame([('bird',    389.0),
                   ('bird',     24.0),
                   ('mammal',   80.5),
                    ('mammal', np.nan)],
                  index=['falcon', 'parrot', 'lion', 'monkey'],
                  columns=('class', 'max_speed'))

In [4]:
df

class  max_speed
falcon    bird      389.0
parrot    bird       24.0
lion    mammal       80.5
monkey  mammal        NaN

In [10]:
# 保留旧的索引
df.reset_index()

index   class  max_speed
0  falcon    bird      389.0
1  parrot    bird       24.0
2    lion  mammal       80.5
3  monkey  mammal        NaN

In [11]:
## 舍弃旧的索引
df.reset_index(drop=True)

class  max_speed
0    bird      389.0
1    bird       24.0
2  mammal       80.5
3  mammal        NaN

In [14]:
## 此时df并没有改变
df

class  max_speed
falcon    bird      389.0
parrot    bird       24.0
lion    mammal       80.5
monkey  mammal        NaN

In [16]:
## 改变df
df.reset_index(drop=True,inplace=True)
df # 此时df已经改变

class  max_speed
0    bird      389.0
1    bird       24.0
2  mammal       80.5
3  mammal        NaN